#########################################################################
#                                                                       #
#  ██████╗ ██╗██╗   ██╗ █████╗ ██╗     ███╗   ███╗██╗███╗  ██╗███████╗  #
#  ██╔══██╗██║██║   ██║██╔══██╗██║     ████╗ ████║██║████╗ ██║██╔════╝  #
#  ██████╔╝██║╚██╗ ██╔╝███████║██║     ██╔████╔██║██║██╔██╗██║█████╗    #
#  ██╔══██╗██║ ╚████╔╝ ██╔══██║██║     ██║╚██╔╝██║██║██║╚████║██╔══╝    #
#  ██║  ██║██║  ╚██╔╝  ██║  ██║███████╗██║ ╚═╝ ██║██║██║ ╚███║███████╗  #
#  ╚═╝  ╚═╝╚═╝   ╚═╝   ╚═╝  ╚═╝╚══════╝╚═╝     ╚═╝╚═╝╚═╝  ╚══╝╚═1═════╝  #
#                                            by Migrate1337     11        #
#########################################################################

mines: