name: RivalMine
<<<<<<< HEAD
version: '1.0.2'
=======
version: '1.0.1git '
>>>>>>> 0efe13a32522842e0126d0175bad05765f1acd53
main: org.migrate1337.rivalmine.RivalMine
api-version: '1.16'
depend: [PlaceholderAPI]
commands:
  rivalmine:
  setpoints:
  createautomine:
<<<<<<< HEAD
  updateautomine:
=======
  updateautomine:
>>>>>>> 0efe13a32522842e0126d0175bad05765f1acd53
